# Generated by Django 4.1.5 on 2023-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
